login: 'login_here'
password: 'password_here'
url: 'url_here'
GTIN_LIST_path: '../source/' 
GTIN_LIST_file: 'GTIN_list.csv'
output_folder: '../source/'
output_file: 'output.xlsx'
Attributes_list: ['PROD_COVER_GTIN', 'PROD_DESC', 'PROD_COUNT', 'WEB_90001854', 'WEB_90001722']
